http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        #permanent: true

  routers:
    jenkins-http:
      entryPoints:
        - web
      rule: "Host(`jenkins.d3vops.me`)"
      middlewares:
        - redirect-to-https
      service: jenkins

    jenkins-https:
      entryPoints:
        - websecure
      rule: "Host(`jenkins.d3vops.me`)"
      tls: true
      service: jenkins

  services:
    jenkins:
      loadBalancer:
        servers:
          - url: "http://jenkins:80"